//
// Created by YuvalFreund on 08.02.24.
//

#ifndef SCALESTOREDB_PAGEIDMANAGERDEFS_H
#define SCALESTOREDB_PAGEIDMANAGERDEFS_H


#define INVALID_SSD_SLOT 0xFFFFFFFFFFFFFFFF
#define INVALID_PAGE_ID 0xFFFFFFFFFFFFFFFF
#define PAGE_ID_MASK 0x000000000000FFFF
#define CONSISTENT_HASHING_WEIGHT 10


#endif //SCALESTOREDB_PAGEIDMANAGERDEFS_H
